# name of the software
name: diffeRenTES

project:
    version: 0.1.0
    download_url: https://github.com/mbraccini/diffeRenTES/releases

license:
    software: GPL-3
    software_url: https://opensource.org/licenses/GPL-3.0

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://github.com/mbraccini/diffeRenTES/
    footer:
      - title: GitHub
        url: https://github.com/mbraccini/diffeRenTES/
      - title: Issues
        url: https://github.com/mbraccini/diffeRenTES/issues?state=open

ui:
    header:
        color1: "#0093FF"
        color2: "#006004"
        trianglify: true

social:
    github:
        user: mbraccini
        repo: diffeRenTES
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

#analytics:
 #   google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
